name = "ai-marketplace"
main = "worker.js"
account_id = "b614a334d81a99630c1b32f074e44a9e"
workers_dev = true
compatibility_date = "2025-01-15"

[vars]
SITE_TITLE = "AI Marketplace"
OPENAI_API_KEY = "AIzaSyC-VESuBdVYAo-nrNgFXmrzd8cdgKLd-OI"
PAYMENT_GATEWAY_API_KEY = "BCR2DN7TRDZ5B2LG"

[env.production]
name = "ai-marketplace-production"
route = "searchenginepro.uk/*"
zone_id = "your_zone_id"
