name = "ai-marketplace"
main = "worker.js"
compatibility_date = "2025-01-31"
workers_dev = true

[vars]
SITE_TITLE = "AI Marketplace"
NODE_ENV = "production"

[env.production]
name = "ai-marketplace-production"
route = "searchenginepro.uk/*"
zone_id = ""

[observability]
enabled = true
